pipeline {
    agent  {
        label 'AGENT-1'
    }
    environment { 
        appVersion = ''
        REGION = "us-east-1"
        ACC_ID = "021891615305"
        PROJECT = "roboshop"
        COMPONENT = "catalogue"
        USERNAME = "acavinash"
    }
    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansicolor('xterm')
    }
    // parameters {
    //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
    //     text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
    //     booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
    //     choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
    //     password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password') 
    // }
    // Build
    stages {
        stage('init') {
            steps {
                script {
                  withAWS(credentials: 'aws-cred', region: "${REGION}") {
                    sh """
                    ls -ltr
                     cd 00-vpc
                     terraform init -reconfigure

                    """

                  }
                }
            }
        }

        stage('plan') {
            steps {
                  withAWS(credentials: 'aws-cred', region: "${REGION}") {
                    sh """
                     cd 00-vpc
                     terraform plan

                    """

                  }
            }
        }

        stage('apply') {
          input {
            message "should we continue?"
            ok "Yes, we should"
            submitter "admin,avinash"
          }
                  withAWS(credentials: 'aws-cred', region: "${REGION}") {
                    sh """
                     cd 00-vpc
                     terraform apply -auto-approve

                    """

                  }
        }
    }

    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'Hello Success'
        }
        failure { 
            echo 'Hello Failure'
        }
    }
}